import React, { useCallback, useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

type KeyItem = {
  id: number; name: string; fingerprint: string; priority: number; admin_enabled: boolean;
  auth_state: string; quota_state: string; control_state: string; pool_role: string;
  quota_window?: string; cooling_until?: string; last_error?: string; last_used_at?: string;
  auto_probe_override?: boolean;
};
type RequestItem = {
  id: string; started_at: string; protocol: string; model: string; stream: boolean;
  final_key_name?: string; attempt_count: number; http_status: number; outcome: string;
  error_class?: string; latency_ms: number; ttft_ms?: number; input_uncached?: number;
  cache_read?: number; cache_write?: number; output_tokens?: number; total_input?: number;
  usage_state: string;
};
type DashboardData = {
  active_key?: KeyItem; key_counts: Record<string, number>; requests: number; successes: number;
  failures: number; failovers: number; input_uncached: number; cache_read: number;
  cache_write: number; output_tokens: number; usage_complete: number;
  timeline: Array<{bucket:string;input_uncached:number;cache_read:number;cache_write:number;output_tokens:number;requests:number}>;
  by_key: Array<{key_id:number;key_name:string;requests:number;successes:number;input_uncached:number;cache_read:number;cache_write:number;output_tokens:number;avg_latency_ms:number}>;
};
type Settings = {auto_probe_enabled:boolean;force_stream_usage:boolean;probe_model:string;probe_interval_sec:number;models_cache_sec:number};

const api = async <T,>(path: string, init?: RequestInit): Promise<T> => {
  const response = await fetch(path, {credentials:"same-origin", ...init, headers:{"Content-Type":"application/json", ...(init?.headers || {})}});
  if (response.status === 204) return undefined as T;
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error?.message || data.error || `HTTP ${response.status}`);
  return data;
};
const formatTokens = (value?: number) => value == null ? "—" : value >= 1_000_000 ? `${(value/1_000_000).toFixed(2)}M` : value >= 1000 ? `${(value/1000).toFixed(1)}K` : String(value);
const formatDate = (value?: string) => value ? new Intl.DateTimeFormat("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(new Date(value)) : "—";
const countdown = (value?: string) => { if(!value)return ""; const seconds=Math.max(0,Math.floor((new Date(value).getTime()-Date.now())/1000)); const d=Math.floor(seconds/86400),h=Math.floor(seconds%86400/3600),m=Math.floor(seconds%3600/60),s=seconds%60; return [d&&`${d}天`,h&&`${h}时`,m&&`${m}分`,`${s}秒`].filter(Boolean).join(" "); };

function Login({onLogin}:{onLogin:()=>void}) {
  const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{await api("/api/admin/login",{method:"POST",body:JSON.stringify({password})});onLogin()}catch(err){setError((err as Error).message)}finally{setBusy(false)}};
  return <main className="login-shell"><section className="login-card"><div className="brand-mark">K</div><p className="eyebrow">OPENCODE GO CONTROL PLANE</p><h1>Keypool</h1><p className="muted">故障转移、额度恢复与缓存效率，一处掌握。</p><form onSubmit={submit}><label>管理员密码<input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="输入 ADMIN_PASSWORD" /></label>{error&&<p className="form-error">{error}</p>}<button className="primary" disabled={busy}>{busy?"正在验证…":"进入控制台"}</button></form></section></main>
}

function App(){
  const [authenticated,setAuthenticated]=useState<boolean|null>(null); const [page,setPage]=useState(location.hash.slice(1)||"dashboard"); const [refresh,setRefresh]=useState(0);
  useEffect(()=>{api("/api/admin/me").then(()=>setAuthenticated(true)).catch(()=>setAuthenticated(false))},[]);
  useEffect(()=>{const handler=()=>setPage(location.hash.slice(1)||"dashboard");addEventListener("hashchange",handler);return()=>removeEventListener("hashchange",handler)},[]);
  useEffect(()=>{if(!authenticated)return;const source=new EventSource("/api/admin/stream");source.addEventListener("tick",()=>setRefresh(v=>v+1));return()=>source.close()},[authenticated]);
  if(authenticated==null)return <div className="boot">正在启动控制台…</div>;
  if(!authenticated)return <Login onLogin={()=>setAuthenticated(true)}/>;
  const logout=async()=>{await api("/api/admin/logout",{method:"POST"});setAuthenticated(false)};
  return <div className="app-shell"><aside><div className="brand"><div className="brand-mark small">K</div><div><strong>Keypool</strong><span>OpenCode Go</span></div></div><nav>{[["dashboard","总览","01"],["keys","密钥池","02"],["requests","请求流水","03"],["settings","设置","04"]].map(([id,label,num])=><a key={id} className={page===id?"active":""} href={`#${id}`}><span>{num}</span>{label}</a>)}</nav><div className="aside-foot"><span className="live-dot"/> 服务运行中<button onClick={logout}>退出</button></div></aside><section className="workspace">{page==="dashboard"&&<Dashboard refresh={refresh}/>} {page==="keys"&&<Keys refresh={refresh}/>} {page==="requests"&&<Requests refresh={refresh}/>} {page==="settings"&&<SettingsPage/>}</section></div>
}

function PageHead({kicker,title,children}:{kicker:string;title:string;children?:React.ReactNode}){return <header className="page-head"><div><p className="eyebrow">{kicker}</p><h1>{title}</h1></div>{children}</header>}
function Stat({label,value,detail,tone}:{label:string;value:string|number;detail:string;tone?:string}){return <article className={`stat ${tone||""}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>}

function Dashboard({refresh}:{refresh:number}){
  const [windowName,setWindowName]=useState("5h"); const [data,setData]=useState<DashboardData|null>(null); const [now,setNow]=useState(Date.now());
  const load=useCallback(()=>api<DashboardData>(`/api/admin/dashboard?window=${windowName}`).then(setData),[windowName]); useEffect(()=>{load()},[load,refresh]); useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]); void now;
  if(!data)return <div className="loading">载入运行数据…</div>;
  const totalInput=data.input_uncached+data.cache_read+data.cache_write; const hit=totalInput?data.cache_read/totalInput*100:0; const coverage=data.requests?data.usage_complete/data.requests*100:0;
  return <><PageHead kicker="LIVE OPERATIONS" title="运行总览"><div className="segmented">{["5h","24h","7d","30d"].map(v=><button className={windowName===v?"selected":""} onClick={()=>setWindowName(v)} key={v}>{v}</button>)}</div></PageHead><section className="hero-status"><div><span className="signal">ACTIVE KEY</span><h2>{data.active_key?.name||"等待首个可用 key"}</h2><p>{data.active_key?`•••• ${data.active_key.fingerprint} · 上次使用 ${formatDate(data.active_key.last_used_at)}`:"添加并验证 key 后自动激活"}</p></div><div className="pool-counts"><div><strong>{data.key_counts.available||0}</strong><span>可用</span></div><div><strong>{data.key_counts.cooling||0}</strong><span>冷却</span></div><div><strong>{data.key_counts.invalid||0}</strong><span>失效</span></div></div></section><section className="stats-grid"><Stat label="请求" value={data.requests} detail={`${data.successes} 成功 · ${data.failures} 失败`}/><Stat label="输入 TOKEN" value={formatTokens(totalInput)} detail={`${formatTokens(data.input_uncached)} 未缓存`}/><Stat label="缓存命中" value={`${hit.toFixed(1)}%`} detail={`${formatTokens(data.cache_read)} cache read`} tone="mint"/><Stat label="输出 TOKEN" value={formatTokens(data.output_tokens)} detail={`${coverage.toFixed(0)}% usage 覆盖率`}/><Stat label="故障转移" value={data.failovers} detail="同一逻辑请求多次尝试" tone={data.failovers?"amber":""}/></section><section className="panel"><div className="panel-head"><div><p className="eyebrow">TOKEN FLOW</p><h3>消耗结构</h3></div><div className="legend"><i className="uncached"/>未缓存<i className="read"/>Cache read<i className="write"/>Cache write<i className="output"/>输出</div></div><TokenChart points={data.timeline}/></section><section className="panel"><div className="panel-head"><div><p className="eyebrow">KEY PERFORMANCE</p><h3>每 key 视角</h3></div><span className="muted">当前窗口</span></div><div className="key-performance">{data.by_key.map(k=>{const input=k.input_uncached+k.cache_read+k.cache_write;const ratio=input?k.cache_read/input*100:0;return <div className="performance-row" key={k.key_id}><div><strong>{k.key_name}</strong><span>{k.requests} 请求 · {k.successes} 成功</span></div><div><small>5H INPUT</small><strong>{formatTokens(input)}</strong></div><div><small>CACHE HIT</small><strong>{ratio.toFixed(1)}%</strong></div><div><small>OUTPUT</small><strong>{formatTokens(k.output_tokens)}</strong></div><div><small>AVG LATENCY</small><strong>{k.avg_latency_ms} ms</strong></div></div>})}</div></section></>
}

function TokenChart({points}:{points:DashboardData["timeline"]}){const max=Math.max(1,...points.map(p=>p.input_uncached+p.cache_read+p.cache_write+p.output_tokens));if(!points.length)return <div className="empty-chart">产生请求后，这里会显示 token 时间线。</div>;return <div className="chart">{points.map(p=>{const values=[[p.input_uncached,"uncached"],[p.cache_read,"read"],[p.cache_write,"write"],[p.output_tokens,"output"]] as const;return <div className="bar-slot" key={p.bucket} title={`${formatDate(p.bucket)} · ${p.requests} 请求`}><div className="bar">{values.map(([v,c])=><i key={c} className={c} style={{height:`${Math.max(v?2:0,v/max*150)}px`}}/>)}</div><span>{new Date(p.bucket).getHours()}:00</span></div>})}</div>}

function Keys({refresh}:{refresh:number}){
  const [keys,setKeys]=useState<KeyItem[]>([]);const [showAdd,setShowAdd]=useState(false);const [error,setError]=useState("");const [now,setNow]=useState(Date.now());const load=useCallback(()=>api<{keys:KeyItem[]}>("/api/admin/keys").then(v=>setKeys(v.keys||[])),[]);useEffect(()=>{load()},[load,refresh]);useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);void now;
  const action=async(path:string,method="POST",body?:unknown)=>{setError("");try{await api(path,{method,body:body?JSON.stringify(body):undefined});await load()}catch(e){setError((e as Error).message)}};
  return <><PageHead kicker="CREDENTIAL ROUTING" title="密钥池"><button className="primary compact" onClick={()=>setShowAdd(!showAdd)}>{showAdd?"取消":"添加 key"}</button></PageHead>{showAdd&&<AddKey onDone={()=>{setShowAdd(false);load()}}/>}{error&&<p className="banner-error">{error}</p>}<section className="keys-list">{keys.length===0&&<div className="empty-state"><strong>池里还没有 key</strong><span>添加第一个独立的 OpenCode Go API key。</span></div>}{keys.map(key=><article className={`key-card ${key.pool_role==="active"?"is-active":""}`} key={key.id}><div className="key-main"><div className="key-title"><span className={`status-dot ${statusTone(key)}`}/><div><h3>{key.name}{key.pool_role==="active"&&<b>ACTIVE</b>}</h3><p>•••• {key.fingerprint} · 优先级 {key.priority}</p></div></div><div className="state-pills"><span>{key.auth_state}</span><span>{key.control_state}</span><span className={key.quota_state}>{key.quota_state}</span>{!key.admin_enabled&&<span className="disabled">disabled</span>}</div></div>{key.quota_state==="cooling"&&<div className="cooldown"><span>{key.quota_window||"额度"}窗口冷却中</span><strong>{countdown(key.cooling_until)}</strong><small>预计 {formatDate(key.cooling_until)} 恢复</small></div>}{key.last_error&&<p className="key-error">{key.last_error}</p>}<div className="key-actions"><button onClick={()=>action(`/api/admin/keys/${key.id}/test`,"POST",{inference:false})}>验证鉴权</button><button onClick={()=>action(`/api/admin/keys/${key.id}/test`,"POST",{inference:true})}>推理探测</button><button disabled={key.pool_role==="active"||key.quota_state==="cooling"} onClick={()=>action(`/api/admin/keys/${key.id}/activate`)}>设为活动</button><button onClick={()=>action(`/api/admin/keys/${key.id}`,"PATCH",{admin_enabled:!key.admin_enabled})}>{key.admin_enabled?"禁用":"启用"}</button><select value={key.auto_probe_override==null?"inherit":key.auto_probe_override?"enabled":"disabled"} onChange={e=>action(`/api/admin/keys/${key.id}`,"PATCH",{auto_probe_mode:e.target.value})}><option value="inherit">探测：继承</option><option value="enabled">探测：开启</option><option value="disabled">探测：关闭</option></select><button className="danger" onClick={()=>confirm(`删除 ${key.name}？`)&&action(`/api/admin/keys/${key.id}`,"DELETE")}>删除</button></div></article>)}</section></>
}
function statusTone(k:KeyItem){if(!k.admin_enabled||k.auth_state==="invalid")return"bad";if(k.quota_state==="cooling")return"warn";if(k.pool_role==="active")return"good";return"idle"}
function AddKey({onDone}:{onDone:()=>void}){const [name,setName]=useState("");const [key,setKey]=useState("");const [priority,setPriority]=useState(100);const [probe,setProbe]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{await api("/api/admin/keys",{method:"POST",body:JSON.stringify({name,key,priority,test_inference:probe})});onDone()}catch(err){setError((err as Error).message)}finally{setBusy(false)}};return <form className="add-key" onSubmit={submit}><div><label>名称<input value={name} onChange={e=>setName(e.target.value)} placeholder="例如 HK Go 01"/></label><label>优先级<input type="number" value={priority} onChange={e=>setPriority(Number(e.target.value))}/></label></div><label>OpenCode Go API key<input required type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="粘贴后将加密保存"/></label><label className="check"><input type="checkbox" checked={probe} onChange={e=>setProbe(e.target.checked)}/>添加后执行一次最小推理探测</label>{error&&<p className="form-error">{error}</p>}<button className="primary" disabled={busy}>{busy?"正在加密并验证…":"保存 key"}</button></form>}

function Requests({refresh}:{refresh:number}){const [items,setItems]=useState<RequestItem[]>([]);const [keyFilter,setKeyFilter]=useState("");const [modelFilter,setModelFilter]=useState("");const load=useCallback(()=>api<{requests:RequestItem[]}>(`/api/admin/requests?limit=100${keyFilter?`&key_id=${keyFilter}`:""}${modelFilter?`&model=${encodeURIComponent(modelFilter)}`:""}`).then(v=>setItems(v.requests||[])),[keyFilter,modelFilter]);useEffect(()=>{load()},[load,refresh]);const models=useMemo(()=>Array.from(new Set(items.map(i=>i.model).filter(Boolean))),[items]);return <><PageHead kicker="REQUEST LEDGER" title="请求流水"><div className="filters"><input placeholder="Key ID" value={keyFilter} onChange={e=>setKeyFilter(e.target.value)}/><select value={modelFilter} onChange={e=>setModelFilter(e.target.value)}><option value="">全部模型</option>{models.map(m=><option key={m}>{m}</option>)}</select></div></PageHead><section className="table-panel"><table><thead><tr><th>时间 / REQUEST ID</th><th>模型</th><th>KEY / 尝试</th><th>未缓存输入</th><th>CACHE READ</th><th>CACHE WRITE</th><th>输出</th><th>命中率</th><th>TTFT / 总耗时</th><th>结果</th></tr></thead><tbody>{items.map(item=>{const total=item.total_input??((item.input_uncached||0)+(item.cache_read||0)+(item.cache_write||0));const hit=total?(item.cache_read||0)/total*100:0;return <tr key={item.id}><td><strong>{formatDate(item.started_at)}</strong><small>{item.id.slice(0,12)}</small></td><td><strong>{item.model||"—"}</strong><small>{item.protocol}{item.stream?" · stream":""}</small></td><td><strong>{item.final_key_name||"—"}</strong><small>{item.attempt_count} attempt</small></td><td>{formatTokens(item.input_uncached)}</td><td className="mint-text">{formatTokens(item.cache_read)}</td><td>{formatTokens(item.cache_write)}</td><td>{formatTokens(item.output_tokens)}</td><td>{item.usage_state==="unavailable"?"—":`${hit.toFixed(1)}%`}</td><td><strong>{item.ttft_ms==null?"—":`${item.ttft_ms}ms`}</strong><small>{item.latency_ms}ms</small></td><td><span className={`result ${item.outcome}`}>{item.http_status||"—"} {item.outcome}</span>{item.error_class&&<small>{item.error_class}</small>}</td></tr>})}</tbody></table>{!items.length&&<div className="empty-table">暂无请求流水。通过代理发送第一个模型请求后会出现在这里。</div>}</section></>}

function SettingsPage(){const [settings,setSettings]=useState<Settings|null>(null);const [saved,setSaved]=useState("");useEffect(()=>{api<Settings>("/api/admin/settings").then(setSettings)},[]);if(!settings)return <div className="loading">载入设置…</div>;const save=async()=>{try{const v=await api<Settings>("/api/admin/settings",{method:"PUT",body:JSON.stringify(settings)});setSettings(v);setSaved("已保存");setTimeout(()=>setSaved(""),2000)}catch(e){setSaved((e as Error).message)}};return <><PageHead kicker="SYSTEM POLICY" title="设置"><button className="primary compact" onClick={save}>保存设置</button></PageHead><section className="settings-grid"><article className="panel"><h3>恢复与探测</h3><Toggle label="自动探测额度恢复" detail="关闭后，到期 key 等待真实业务请求或手动探测。" value={settings.auto_probe_enabled} onChange={v=>setSettings({...settings,auto_probe_enabled:v})}/><label>探测模型<input value={settings.probe_model} onChange={e=>setSettings({...settings,probe_model:e.target.value})}/><small>使用 OpenAI-compatible 接口发送 2 个输出 token 的最小请求。</small></label><label>未知恢复时间的探测间隔（秒）<input type="number" min="60" value={settings.probe_interval_sec} onChange={e=>setSettings({...settings,probe_interval_sec:Number(e.target.value)})}/></label></article><article className="panel"><h3>统计与模型目录</h3><Toggle label="请求流式 usage" detail="为兼容的 OpenAI 流请求补充 include_usage；若某模型拒绝该参数，可在此关闭。" value={settings.force_stream_usage} onChange={v=>setSettings({...settings,force_stream_usage:v})}/><label>模型列表缓存（秒）<input type="number" min="30" value={settings.models_cache_sec} onChange={e=>setSettings({...settings,models_cache_sec:Number(e.target.value)})}/><small>模型列表不受推理 quota 状态影响，并在上游故障时返回最后一次成功缓存。</small></label></article><article className="panel deployment"><h3>接入信息</h3><dl><div><dt>OpenAI-compatible Base URL</dt><dd>{location.origin}/v1</dd></div><div><dt>Anthropic Base URL</dt><dd>{location.origin}/v1</dd></div><div><dt>鉴权</dt><dd>Authorization: Bearer &lt;PROXY_TOKEN&gt;</dd></div><div><dt>监听</dt><dd>0.0.0.0:8080</dd></div></dl></article></section>{saved&&<div className="toast">{saved}</div>}</>}
function Toggle({label,detail,value,onChange}:{label:string;detail:string;value:boolean;onChange:(v:boolean)=>void}){return <button className="toggle-row" onClick={()=>onChange(!value)}><div><strong>{label}</strong><span>{detail}</span></div><i className={value?"on":""}><b/></i></button>}

createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
